INSERT INTO "public"."categorie" ("id", "description", "image", "nom", "slug", "rayon_id") VALUES
                                                                                               (1, 'Electronics and Gadgets', 'electronics.jpg', 'Electronics', 'electronics', 1),
                                                                                               (2, 'Clothing and Apparel', 'clothing.jpg', 'Clothing', 'clothing', 1),
                                                                                               (3, 'Home and Furniture', 'furniture.jpg', 'Home & Furniture', 'home-furniture', 1),
                                                                                               (4, 'Books and Literature', 'books.jpg', 'Books', 'books', 1),
                                                                                               (5, 'Sports and Outdoors', 'sports.jpg', 'Sports & Outdoors', 'sports-outdoors', 1),
                                                                                               (6, 'Beauty and Personal Care', 'beauty.jpg', 'Beauty', 'beauty', 1),
                                                                                               (7, 'Toys and Games', 'toys.jpg', 'Toys & Games', 'toys-games', 1),
                                                                                               (8, 'Food and Groceries', 'food.jpg', 'Food & Groceries', 'food-groceries', 1),
                                                                                               (9, 'Automotive', 'automotive.jpg', 'Automotive', 'automotive', 1),
                                                                                               (10, 'Health and Wellness', 'health.jpg', 'Health & Wellness', 'health-wellness', 1),
                                                                                               (11, 'Jewelry and Accessories', 'jewelry.jpg', 'Jewelry', 'jewelry', 1),
                                                                                               (12, 'Pet Supplies', 'pets.jpg', 'Pet Supplies', 'pet-supplies', 1),
                                                                                               (13, 'Music and Instruments', 'music.jpg', 'Music & Instruments', 'music-instruments', 1),
                                                                                               (14, 'Movies and Entertainment', 'movies.jpg', 'Movies', 'movies', 1),
                                                                                               (15, 'Computers and Accessories', 'computers.jpg', 'Computers', 'computers', 1),
                                                                                               (16, 'Art and Crafts', 'art.jpg', 'Art & Crafts', 'art-crafts', 1),
                                                                                               (17, 'Travel and Luggage', 'travel.jpg', 'Travel & Luggage', 'travel-luggage', 1),
                                                                                               (18, 'Fitness and Exercise', 'fitness.jpg', 'Fitness', 'fitness', 1),
                                                                                               (19, 'Home Improvement', 'home-improvement.jpg', 'Home Improvement', 'home-improvement', 1),
                                                                                               (20, 'Garden and Outdoor Living', 'garden.jpg', 'Garden', 'garden', 1),
                                                                                               (21, 'Electrical Appliances', 'appliances.jpg', 'Appliances', 'appliances', 1),
                                                                                               (22, 'Stationery and Office Supplies', 'stationery.jpg', 'Stationery', 'stationery', 1),
                                                                                               (23, 'Baby and Kids', 'baby.jpg', 'Baby & Kids', 'baby-kids', 1),
                                                                                               (24, 'Fashion Accessories', 'fashion-accessories.jpg', 'Fashion Accessories', 'fashion-accessories', 1),
                                                                                               (25, 'Camping and Hiking', 'camping.jpg', 'Camping & Hiking', 'camping-hiking', 1),
                                                                                               (26, 'Cookware and Kitchen Appliances', 'cookware.jpg', 'Cookware', 'cookware', 1),
                                                                                               (27, 'Party Supplies', 'party.jpg', 'Party Supplies', 'party-supplies', 1),
                                                                                               (28, 'Watches', 'watches.jpg', 'Watches', 'watches', 1),
                                                                                               (29, 'Drones and Tech Gadgets', 'drones.jpg', 'Drones & Tech Gadgets', 'drones-tech-gadgets', 1),
                                                                                               (30, 'DIY and Craft Supplies', 'diy-crafts.jpg', 'DIY & Craft Supplies', 'diy-craft-supplies', 1),
                                                                                               (31, 'Instruments and Audio Equipment', 'audio.jpg', 'Audio Equipment', 'audio-equipment', 1),
                                                                                               (32, 'Home Decor', 'home-decor.jpg', 'Home Decor', 'home-decor', 1),
                                                                                               (33, 'Outdoor Clothing', 'outdoor-clothing.jpg', 'Outdoor Clothing', 'outdoor-clothing', 1),
                                                                                               (34, 'Smart Home Devices', 'smart-home.jpg', 'Smart Home Devices', 'smart-home-devices', 1),
                                                                                               (35, 'Sunglasses', 'sunglasses.jpg', 'Sunglasses', 'sunglasses', 1),
                                                                                               (36, 'Bathroom Essentials', 'bathroom.jpg', 'Bathroom Essentials', 'bathroom-essentials', 1),
                                                                                               (37, 'Collectibles and Memorabilia', 'collectibles.jpg', 'Collectibles', 'collectibles', 1),
                                                                                               (38, 'Educational Toys', 'educational-toys.jpg', 'Educational Toys', 'educational-toys', 1),
                                                                                               (39, 'Smartphones and Accessories', 'smartphones.jpg', 'Smartphones', 'smartphones', 1),
                                                                                               (40, 'Fishing Gear', 'fishing.jpg', 'Fishing Gear', 'fishing-gear', 1);
