INSERT INTO "public"."ville" ("id", "code_postal", "nom") VALUES
                                                              (1, '4600', 'SAFI'),
                                                              (2, '20000', 'CASABLANCA'),
                                                              (3, '50000', 'MARRAKECH'),
                                                              (4, '90000', 'TANGIER'),
                                                              (5, '30000', 'FES'),
                                                              (6, '60000', 'RABAT'),
                                                              (7, '80000', 'AGADIR'),
                                                              (8, '70000', 'MEKNES'),
                                                              (9, '10000', 'TETOUAN'),
                                                              (10, '40000', 'OUARZAZATE'),
                                                              (11, '46050', 'ESSAOUIRA'),
                                                              (12, '35000', 'KENITRA'),
                                                              (13, '52000', 'BENI MELLAL'),
                                                              (14, '93000', 'LARACHE'),
                                                              (15, '30050', 'AL HOCEIMA'),
                                                              (16, '54000', 'SALE'),
                                                              (17, '24000', 'TAZA'),
                                                              (18, '32000', 'KHENIFRA'),
                                                              (19, '46060', 'EL JADIDA'),
                                                              (20, '92000', 'OUJDA'),
                                                              (21, '22000', 'BENSLIMANE'),
                                                              (22, '30060', 'NADOR'),
                                                              (23, '80050', 'TIZNIT'),
                                                              (24, '50050', 'ASILAH'),
                                                              (25, '26000', 'SEFROU'),
                                                              (26, '50030', 'CHEFCHAOUEN'),
                                                              (27, '24050', 'OUED ZEM'),
                                                              (28, '43000', 'KHOURIBGA'),
                                                              (29, '45000', 'BERKANE'),
                                                              (30, '23000', 'EL KELAA DES SRAGHNA'),
                                                              (31, '46040', 'SKHIRATE'),
                                                              (32, '30040', 'MIDELT'),
                                                              (33, '44000', 'GUELMIM'),
                                                              (34, '13000', 'TAOURIRT'),
                                                              (35, '23050', 'KHOURIBGA'),
                                                              (36, '23040', 'ZAGORA'),
                                                              (37, '41000', 'BEN GUERIR'),
                                                              (38, '11000', 'SALE'),
                                                              (39, '20050', 'CASABLANCA'),
                                                              (40, '27000', 'TEMARA'),
                                                              (41, '53000', 'ERRACHIDIA'),
                                                              (42, '46020', 'KHEMISSET'),
                                                              (43, '30020', 'MIDELT'),
                                                              (44, '42000', 'OUARZAZATE'),
                                                              (45, '90050', 'TETOUAN'),
                                                              (46, '46070', 'SKHIRATE'),
                                                              (47, '50060', 'KHOURIBGA'),
                                                              (48, '23030', 'KHEMISSET'),
                                                              (49, '13050', 'TAOURIRT'),
                                                              (50, '42050', 'OUARZAZATE'),
                                                              (51, '52050', 'BENI MELLAL'),
                                                              (52, '46080', 'SKHIRATE'),
                                                              (53, '54050', 'SALE'),
                                                              (54, '54020', 'SALE'),
                                                              (55, '20040', 'CASABLANCA'),
                                                              (56, '35050', 'KENITRA'),
                                                              (57, '23020', 'EL KELAA DES SRAGHNA'),
                                                              (58, '80020', 'TIZNIT'),
                                                              (59, '54040', 'SALE'),
                                                              (60, '60050', 'RABAT'),
                                                              (61, '52040', 'BENI MELLAL'),
                                                              (62, '50020', 'ASILAH'),
                                                              (63, '30030', 'FES'),
                                                              (64, '30010', 'FES'),
                                                              (65, '30070', 'FES'),
                                                              (66, '36000', 'TAROUDANT'),
                                                              (67, '26050', 'SEFROU'),
                                                              (68, '42040', 'OUARZAZATE'),
                                                              (69, '30080', 'FES'),
                                                              (70, '60020', 'RABAT'),
                                                              (71, '30090', 'FES'),
                                                              (72, '54010', 'SALE'),
                                                              (73, '10020', 'TETOUAN'),
                                                              (74, '54030', 'SALE'),
                                                              (75, '10010', 'TETOUAN'),
                                                              (76, '60040', 'RABAT'),
                                                              (77, '53050', 'ERRACHIDIA'),
                                                              (78, '44050', 'GUELMIM'),
                                                              (79, '20030', 'CASABLANCA'),
                                                              (80, '41050', 'BEN GUERIR'),
                                                              (81, '50040', 'ASILAH'),
                                                              (82, '13040', 'TAOURIRT'),
                                                              (83, '46030', 'SKHIRATE'),
                                                              (84, '46090', 'SKHIRATE'),
                                                              (85, '46010', 'SKHIRATE'),
                                                              (86, '30012', 'FES'),
                                                              (87, '80040', 'TIZNIT'),
                                                              (88, '20010', 'CASABLANCA'),
                                                              (89, '90010', 'TETOUAN'),
                                                              (90, '52030', 'BENI MELLAL'),
                                                              (91, '22050', 'BENSLIMANE'),
                                                              (92, '54060', 'SALE'),
                                                              (93, '50010', 'ASILAH'),
                                                              (94, '23010', 'EL KELAA DES SRAGHNA'),
                                                              (95, '53020', 'ERRACHIDIA'),
                                                              (96, '42030', 'OUARZAZATE'),
                                                              (97, '54070', 'SALE'),
                                                              (98, '52020', 'BENI MELLAL'),
                                                              (99, '30014', 'FES'),
                                                              (100, '52010', 'BENI MELLAL');
