INSERT INTO "public"."rayon" ("id", "description", "image", "nom") VALUES
                                                                       (2, 'Electronics Gadgets', 'https://example.com/electronics_image.jpg', 'Electronics Section'),
                                                                       (3, 'Mens Fashion', 'https://example.com/mens_fashion_image.jpg', 'Mens Fashion'),
                                                                       (4, 'Womens Fashion', 'https://example.com/womens_fashion_image.jpg', 'Womens Fashion'),
                                                                       (5, 'Home and Kitchen', 'https://example.com/home_kitchen_image.jpg', 'Home and Kitchen'),
                                                                       (6, 'Books and Stationery', 'https://example.com/books_image.jpg', 'Books and Stationery'),
                                                                       (7, 'Toys and Games', 'https://example.com/toys_games_image.jpg', 'Toys and Games'),
                                                                       (8, 'Beauty and Personal Care', 'https://example.com/beauty_image.jpg', 'Beauty and Personal Care'),
                                                                       (9, 'Automotive', 'https://example.com/automotive_image.jpg', 'Automotive Section'),
                                                                       (10, 'Outdoor and Garden', 'https://example.com/outdoor_image.jpg', 'Outdoor and Garden'),
                                                                       (11, 'Health and Fitness', 'https://example.com/health_fitness_image.jpg', 'Health and Fitness'),
                                                                       (12, 'Pet Supplies', 'https://example.com/pet_supplies_image.jpg', 'Pet Supplies'),
                                                                       (13, 'Jewelry and Accessories', 'https://example.com/jewelry_image.jpg', 'Jewelry and Accessories'),
                                                                       (14, 'Office Products', 'https://example.com/office_products_image.jpg', 'Office Products'),
                                                                       (15, 'Musical Instruments', 'https://example.com/musical_instruments_image.jpg', 'Musical Instruments'),
                                                                       (16, 'Tools and Home Improvement', 'https://example.com/tools_image.jpg', 'Tools and Home Improvement'),
                                                                       (17, 'Baby Products', 'https://example.com/baby_products_image.jpg', 'Baby Products'),
                                                                       (18, 'Grocery', 'https://example.com/grocery_image.jpg', 'Grocery Section'),
                                                                       (19, 'Luggage and Travel Gear', 'https://example.com/luggage_image.jpg', 'Luggage and Travel Gear'),
                                                                       (20, 'Furniture', 'https://example.com/furniture_image.jpg', 'Furniture Section'),
                                                                       (21, 'Cameras and Photography', 'https://example.com/cameras_image.jpg', 'Cameras and Photography'),
                                                                       (22, 'Industrial and Scientific', 'https://example.com/industrial_scientific_image.jpg', 'Industrial and Scientific'),
                                                                       (23, 'Arts, Crafts, and Sewing', 'https://example.com/arts_crafts_image.jpg', 'Arts, Crafts, and Sewing'),
                                                                       (24, 'Movies and TV Shows', 'https://example.com/movies_tv_shows_image.jpg', 'Movies and TV Shows'),
                                                                       (25, 'Video Games', 'https://example.com/video_games_image.jpg', 'Video Games'),
                                                                       (26, 'Cell Phones and Accessories', 'https://example.com/cell_phones_image.jpg', 'Cell Phones and Accessories'),
                                                                       (27, 'Computers and Accessories', 'https://example.com/computers_image.jpg', 'Computers and Accessories'),
                                                                       (28, 'Hobbies', 'https://example.com/hobbies_image.jpg', 'Hobbies'),
                                                                       (29, 'Sportswear', 'https://example.com/sportswear_image.jpg', 'Sportswear'),
                                                                       (30, 'Smart Home', 'https://example.com/smart_home_image.jpg', 'Smart Home'),
                                                                       (40, 'Watches', 'https://example.com/watches_image.jpg', 'Watches');